### PR TITLE
output swagger json instead of writing to a file, describe response mode

### PR DESCRIPTION
**Pull request by bkulyk**
* don't write the output to a swagger.json file, return the output instead (this would be a breaking change for user)
* add ability to describe the 200 response model
* there has been some other refactoring
* added unit tests

### CODE REVIEW

**Comment by bkulyk** [comment]
Since this is a bit of a breaking change I will update the README.

**Comment by bkulyk** [comment]
@vforv can you please review?

**Comment by vforv** [comment]
Will do... Thanks for update

**Comment by bkulyk** [comment]
Any chance you can review this?

**Comment by vforv** [comment]
What is the purpose of returning swagger object instead of writing it to the file?

**Comment by bkulyk** [comment]
For me it had multiple purposes:

1. every time the app started it would write the json file and nodemon would find the change and restart the application into an infinite loop.  Which I could have avoided by telling nodemon to ignore the file, but I might not be the only person suffering from this problem

2. I wanted to pass the object off to another library, and it could have read it from the file system and passed it to the other library (in this case a wrapped version of `swagger-ui-express`), but I had no use for it to be on the file system on the first place.

**Comment by vforv** [comment]
There are use cases where you need swagger.json file and some other plugins already using that file...

Nodemon should not watch node_modules folder for changes anyway.

Why you don't use https://github.com/vforv/express-joi-simple plugin?

**Comment by bkulyk** [comment]
It generates into the project folder not into node_modules

I think it's generally not a great practice to rewrite a file everytime a
path is discovered.

As for the other plugins, if we were to increment the major version number
it should prevent breaking then until the explicitly upgrade.

I was using express-joi-simple it had issues too

**Comment by bkulyk** [comment]
I'll go back and add some better backward compatibility.

**Comment by bkulyk** [comment]
I changed the module.exports to be able to export the class instance with the original behavior (writing to the file system) as well as a second version, that returns the output instead. 

It will not create both instances unless they are both being used.

**Comment by vforv** [comment]
You porbably have some dist folder which nodemon watch, just exclude it...

What was issue with express-joi-simple?

Looks better now. Could you increase version number to the 2.0.0?

**Comment by bkulyk** [comment]
I don't use a dist folder in my code, so the swagger.json generated into the root of the project, which isn't ideal, also since it writes the file every time it discovers a route, it's writing the file, it's writing a dozen times slowing down the application boot time (though not by a lot)

If I recall correctly, the big issue I had with express-joi-simple,  was json file contents was embedded into the html, I wanted it as a /swagger.json endpoint, and I could have used a static file endpoint to add it, but it was all a little more trouble than I think it should have been.  This PR goes a lot way to fix that for me, so thanks for considering it.

I have updated the version number, as you suggested.

**Pull request merged**
